baseURL = 'https://skullfisher87.github.io/stark/'
languageCode = 'es'
title = 'Stark'
theme = 'ananke'
DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
  #    unsafe = true

[languages]
  [languages.es]
   title = 'Mi sitio ES'
   weight = 1
   contentDir = 'content/es'
   #lenguageCode = 'es'
  [languages.en]
   title = 'My site EN'
   weight = '2'
   contentDir = 'content/en'
   #lenguageCode = 'en-US'
   
[params]
  text_color = ""
  author = ""
  favicon = "stark_2022.png"
  site_logo = "stark_2022.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/theNewDynamic"
[[params.ananke_socials]]
  name = "youtube"
  url = "https://github.com/theNewDynamic"
[[params.ananke_socials]]
  name = 'facebook'
[[params.ananke_socials]]
 name = 'instagram'

[services.disqus]
  shortname = 'YOURSHORTNAME'

