baseURL = 'https://stark.com.py'
languageCode = 'es'
title = 'Stark'
theme = 'ananke'
DefaultContentLanguage = "es"


Paginate = 3 
recent_posts_number = 3

googleAnalytics = ""
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
  #    unsafe = true

[languages]
  [languages.es]
   title = 'Stark Tecnología'
   weight = 1
   contentDir = 'content/es'
   
  [languages.en]
   title = 'Stark Tecnology'
   weight = '2'
   contentDir = 'content/en'
   
[params]

  custom_css = ["custom.css"]
  text_color = "black"
  #author = "Stark"
  favicon = "favicon/android-chrome-512x512.png"
  site_logo = "LOGO-STARK.png"
  site_footer_logo = "STARK-blanco.png"
  body_classes = "Roboto"
  background_footer_color_class = "grey-stark"
  
 
[[params.ananke_socials]]
  name = "linkedin"
    url = "https://www.linkedin.com/company/stark-tecnolog-a-sa/"
#[[params.ananke_socials]]
  #name = "facebook"
    #url = "#"
#[[params.ananke_socials]]
  #name = "instagram"
    #url = "#"
#[[params.ananke_socials]]
  #name = "youtube"
    #url = "#"

